# Generated by Django 2.2.7 on 2019-12-20 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orders.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('code', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coin_amount', models.FloatField(default=0.0)),
                ('price', models.IntegerField(default=0)),
                ('order_reference', models.CharField(default=orders.models.genrandom, max_length=35)),
                ('payment_reference', models.CharField(blank=True, max_length=35, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('wallet', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expired', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('Pending', 'pending'), ('Paid', 'paid'), ('Cancelled', 'cancelled'), ('Processing', 'Processing'), ('Failed', 'failed')], default='Pending', max_length=50)),
                ('order_type', models.CharField(choices=[('SELL', 'Sell'), ('BUY', 'Buy'), ('Unspecified', 'Unspecified')], default='Unspecified', max_length=50)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Coin', to='orders.Coins')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('order_status', models.CharField(choices=[('Pending', 'pending'), ('Paid', 'paid'), ('Failed', 'failed')], default='Pending', max_length=50)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='orders.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
