# Generated by Django 2.2.7 on 2019-11-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191115_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Paid', 'paid'), ('Cancelled', 'cancelled'), ('Failed', 'failed')], default='Pending', max_length=50),
        ),
    ]
