# Generated by Django 2.2.7 on 2019-11-15 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
