# Generated by Django 2.2.7 on 2019-11-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('SELL', 'Sell'), ('BUY', 'Buy'), ('Unspecified', 'Unspecified')], default='Unspecified', max_length=50),
        ),
    ]
