# Generated by Django 2.2.7 on 2019-11-25 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_reference',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
