# Generated by Django 2.2.7 on 2019-11-25 13:00

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.CharField(default=orders.models.genrandom, max_length=100),
        ),
    ]
