# Generated by Django 2.2.7 on 2019-11-29 13:00

from django.db import migrations, models
import orders.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191125_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_reference',
            field=models.CharField(default=orders.models.genrandom, max_length=35),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Paid', 'paid'), ('Cancelled', 'cancelled'), ('Processing', 'Processing'), ('Failed', 'failed')], default='Pending', max_length=50),
        ),
    ]
